@echo off
REM This batch file runs and plots data collected
REM by RSM plotting software for the Rigaku X-ray machine
REM
REM Example of usage:
REM		\current_directory>bat_testing.bat RSM_example.txt
REM
REM All files used below must be in the directory where
REM the RMS files to plot are located
REM 
REM To run the software provided, you need MATLAB 2014B or later 
REM or Octave and Perl installed (note: Octave is the Linux 
REM freeware version of MATLAB. Also, Perl is automatically 
REM installed for Linux distributions)

REM ################################################
REM RSM_parse.pl is looking for an exported RSM text file from
REM the Rigaku 3D Explore software
REM
REM Note: you can select the x,y coordinate system, e.g. Qx Qz, in 
REM the Rigaku software under Process/Coordinate Convert. 
REM Regardless of the conversion, the RSM will still be in a 
REM relative measurement to the substrate peak, so you need to add 
REM the correct offset for your particular substrate!
REM
REM The script emoves the headers from the RSM file and generates 
REM an output csv file for the two data columns in a csv format. 
REM Outut file is called RSM_parse_output.csv. This file is fed 
REM into RSM_plot.m to plot its contents
REM 
REM For example use the following if you have an input file and
REM want to run the perl script standalone from this bat file: 
REM 	perl RSM_parse.pl "my_input_values.txt"
REM		 			or
REM 	perl RSM_parse.pl my_input_values.txt
REM 
REM This perl script will use the input called from the command line
REM See "Example of usage above"
perl RSM_parse.pl %1

REM ################################################
REM Plots the output RSM plot in MATLAB with RSM_plot.m function
REM Input arguments passed into the function are the two output files
REM generated by RSM_parse.pl
REM NOTE: this requires MATLAB 2014B or later to run some of
REM the plotting commands
MATLAB -r "RSM_plot('RSM_plot_output_params.csv','RSM_plot_output.csv')"
